const {
  getAgentBB,
  getAgentsBB,
  loadAgentBB,
  createAgentBB,
  updateAgentBB,
  deleteAgentBB,
  deleteUserAgentsBB,
  revertAgentVersionBB,
  updateAgentProjectsBB,
  countPromotedAgentsBB,
  addAgentResourceFileBB,
  getListAgentsByAccessBB,
  removeAgentResourceFilesBB,
} = require('@librechat/api');

module.exports = {
  getAgent: getAgentBB,
  getAgents: getAgentsBB,
  loadAgent: loadAgentBB,
  createAgent: createAgentBB,
  updateAgent: updateAgentBB,
  deleteAgent: deleteAgentBB,
  deleteUserAgents: deleteUserAgentsBB,
  revertAgentVersion: revertAgentVersionBB,
  updateAgentProjects: updateAgentProjectsBB,
  countPromotedAgents: countPromotedAgentsBB,
  addAgentResourceFile: addAgentResourceFileBB,
  getListAgentsByAccess: getListAgentsByAccessBB,
  removeAgentResourceFiles: removeAgentResourceFilesBB,
};
