const {
  getPromptGroupsBB,
  deletePromptGroupBB,
  getAllPromptGroupsBB,
  getListPromptGroupsByAccessBB,
  createPromptGroupBB,
  savePromptBB,
  getPromptsBB,
  getPromptBB,
  getRandomPromptGroupsBB,
  getPromptGroupsWithPromptsBB,
  getPromptGroupBB,
  deletePromptBB,
  deleteUserPromptsBB,
  updatePromptGroupBB,
  makePromptProductionBB,
  updatePromptLabelsBB,
} = require('@librechat/api');

module.exports = {
  getPromptGroups: getPromptGroupsBB,
  deletePromptGroup: deletePromptGroupBB,
  getAllPromptGroups: getAllPromptGroupsBB,
  getListPromptGroupsByAccess: getListPromptGroupsByAccessBB,
  createPromptGroup: createPromptGroupBB,
  savePrompt: savePromptBB,
  getPrompts: getPromptsBB,
  getPrompt: getPromptBB,
  getRandomPromptGroups: getRandomPromptGroupsBB,
  getPromptGroupsWithPrompts: getPromptGroupsWithPromptsBB,
  getPromptGroup: getPromptGroupBB,
  deletePrompt: deletePromptBB,
  deleteUserPrompts: deleteUserPromptsBB,
  updatePromptGroup: updatePromptGroupBB,
  makePromptProduction: makePromptProductionBB,
  updatePromptLabels: updatePromptLabelsBB,
};
